artifacts_root: artifacts #one artifacts root
#whenever i execute my training pipline it will create one folder 'artific'
#it will save all the ml part

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Merryyori/DATA/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
